// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/acca/accounts.proto

package acca

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCurrencyRequest struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCurrencyRequest) Reset()         { *m = CreateCurrencyRequest{} }
func (m *CreateCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCurrencyRequest) ProtoMessage()    {}
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{0}
}
func (m *CreateCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCurrencyRequest.Unmarshal(m, b)
}
func (m *CreateCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCurrencyRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCurrencyRequest.Merge(dst, src)
}
func (m *CreateCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCurrencyRequest.Size(m)
}
func (m *CreateCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCurrencyRequest proto.InternalMessageInfo

func (m *CreateCurrencyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateCurrencyRequest) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type CreateCurrencyResponse struct {
	CurrencyId           int64    `protobuf:"varint,1,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCurrencyResponse) Reset()         { *m = CreateCurrencyResponse{} }
func (m *CreateCurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCurrencyResponse) ProtoMessage()    {}
func (*CreateCurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{1}
}
func (m *CreateCurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCurrencyResponse.Unmarshal(m, b)
}
func (m *CreateCurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCurrencyResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCurrencyResponse.Merge(dst, src)
}
func (m *CreateCurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCurrencyResponse.Size(m)
}
func (m *CreateCurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCurrencyResponse proto.InternalMessageInfo

func (m *CreateCurrencyResponse) GetCurrencyId() int64 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

type GetCurrenciesRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrenciesRequest) Reset()         { *m = GetCurrenciesRequest{} }
func (m *GetCurrenciesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrenciesRequest) ProtoMessage()    {}
func (*GetCurrenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{2}
}
func (m *GetCurrenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrenciesRequest.Unmarshal(m, b)
}
func (m *GetCurrenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrenciesRequest.Marshal(b, m, deterministic)
}
func (dst *GetCurrenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrenciesRequest.Merge(dst, src)
}
func (m *GetCurrenciesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrenciesRequest.Size(m)
}
func (m *GetCurrenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrenciesRequest proto.InternalMessageInfo

func (m *GetCurrenciesRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetCurrenciesResponse struct {
	Currencies           []*Currency `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCurrenciesResponse) Reset()         { *m = GetCurrenciesResponse{} }
func (m *GetCurrenciesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrenciesResponse) ProtoMessage()    {}
func (*GetCurrenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{3}
}
func (m *GetCurrenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrenciesResponse.Unmarshal(m, b)
}
func (m *GetCurrenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrenciesResponse.Marshal(b, m, deterministic)
}
func (dst *GetCurrenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrenciesResponse.Merge(dst, src)
}
func (m *GetCurrenciesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrenciesResponse.Size(m)
}
func (m *GetCurrenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrenciesResponse proto.InternalMessageInfo

func (m *GetCurrenciesResponse) GetCurrencies() []*Currency {
	if m != nil {
		return m.Currencies
	}
	return nil
}

type CreateAccountRequest struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CurrencyId           int64             `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{4}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateAccountRequest) GetCurrencyId() int64 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *CreateAccountRequest) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type CreateAccountResponse struct {
	AccId                int64    `protobuf:"varint,1,opt,name=acc_id,json=accId,proto3" json:"acc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{5}
}
func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(dst, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccId() int64 {
	if m != nil {
		return m.AccId
	}
	return 0
}

type GetAccountsByIDsRequest struct {
	AccIds               []int64  `protobuf:"varint,1,rep,packed,name=acc_ids,json=accIds,proto3" json:"acc_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsByIDsRequest) Reset()         { *m = GetAccountsByIDsRequest{} }
func (m *GetAccountsByIDsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsByIDsRequest) ProtoMessage()    {}
func (*GetAccountsByIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{6}
}
func (m *GetAccountsByIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsByIDsRequest.Unmarshal(m, b)
}
func (m *GetAccountsByIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsByIDsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountsByIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsByIDsRequest.Merge(dst, src)
}
func (m *GetAccountsByIDsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsByIDsRequest.Size(m)
}
func (m *GetAccountsByIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsByIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsByIDsRequest proto.InternalMessageInfo

func (m *GetAccountsByIDsRequest) GetAccIds() []int64 {
	if m != nil {
		return m.AccIds
	}
	return nil
}

type GetAccountsByIDsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsByIDsResponse) Reset()         { *m = GetAccountsByIDsResponse{} }
func (m *GetAccountsByIDsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsByIDsResponse) ProtoMessage()    {}
func (*GetAccountsByIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{7}
}
func (m *GetAccountsByIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsByIDsResponse.Unmarshal(m, b)
}
func (m *GetAccountsByIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsByIDsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountsByIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsByIDsResponse.Merge(dst, src)
}
func (m *GetAccountsByIDsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsByIDsResponse.Size(m)
}
func (m *GetAccountsByIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsByIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsByIDsResponse proto.InternalMessageInfo

func (m *GetAccountsByIDsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetAccountsByKeyRequest struct {
	Key                  int64    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsByKeyRequest) Reset()         { *m = GetAccountsByKeyRequest{} }
func (m *GetAccountsByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsByKeyRequest) ProtoMessage()    {}
func (*GetAccountsByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{8}
}
func (m *GetAccountsByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsByKeyRequest.Unmarshal(m, b)
}
func (m *GetAccountsByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsByKeyRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountsByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsByKeyRequest.Merge(dst, src)
}
func (m *GetAccountsByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsByKeyRequest.Size(m)
}
func (m *GetAccountsByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsByKeyRequest proto.InternalMessageInfo

func (m *GetAccountsByKeyRequest) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type GetAccountsByKeyResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsByKeyResponse) Reset()         { *m = GetAccountsByKeyResponse{} }
func (m *GetAccountsByKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsByKeyResponse) ProtoMessage()    {}
func (*GetAccountsByKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{9}
}
func (m *GetAccountsByKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsByKeyResponse.Unmarshal(m, b)
}
func (m *GetAccountsByKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsByKeyResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountsByKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsByKeyResponse.Merge(dst, src)
}
func (m *GetAccountsByKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsByKeyResponse.Size(m)
}
func (m *GetAccountsByKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsByKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsByKeyResponse proto.InternalMessageInfo

func (m *GetAccountsByKeyResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetAccountsByUserIDRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsByUserIDRequest) Reset()         { *m = GetAccountsByUserIDRequest{} }
func (m *GetAccountsByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsByUserIDRequest) ProtoMessage()    {}
func (*GetAccountsByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{10}
}
func (m *GetAccountsByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsByUserIDRequest.Unmarshal(m, b)
}
func (m *GetAccountsByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsByUserIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountsByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsByUserIDRequest.Merge(dst, src)
}
func (m *GetAccountsByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsByUserIDRequest.Size(m)
}
func (m *GetAccountsByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsByUserIDRequest proto.InternalMessageInfo

func (m *GetAccountsByUserIDRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetAccountsByUserIDResponse struct {
	UserAccounts         *UserAccounts `protobuf:"bytes,1,opt,name=user_accounts,json=userAccounts,proto3" json:"user_accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAccountsByUserIDResponse) Reset()         { *m = GetAccountsByUserIDResponse{} }
func (m *GetAccountsByUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsByUserIDResponse) ProtoMessage()    {}
func (*GetAccountsByUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounts_0e69909454bdbf9b, []int{11}
}
func (m *GetAccountsByUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsByUserIDResponse.Unmarshal(m, b)
}
func (m *GetAccountsByUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsByUserIDResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountsByUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsByUserIDResponse.Merge(dst, src)
}
func (m *GetAccountsByUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsByUserIDResponse.Size(m)
}
func (m *GetAccountsByUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsByUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsByUserIDResponse proto.InternalMessageInfo

func (m *GetAccountsByUserIDResponse) GetUserAccounts() *UserAccounts {
	if m != nil {
		return m.UserAccounts
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateCurrencyRequest)(nil), "acca.CreateCurrencyRequest")
	proto.RegisterMapType((map[string]string)(nil), "acca.CreateCurrencyRequest.MetaEntry")
	proto.RegisterType((*CreateCurrencyResponse)(nil), "acca.CreateCurrencyResponse")
	proto.RegisterType((*GetCurrenciesRequest)(nil), "acca.GetCurrenciesRequest")
	proto.RegisterType((*GetCurrenciesResponse)(nil), "acca.GetCurrenciesResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "acca.CreateAccountRequest")
	proto.RegisterMapType((map[string]string)(nil), "acca.CreateAccountRequest.MetaEntry")
	proto.RegisterType((*CreateAccountResponse)(nil), "acca.CreateAccountResponse")
	proto.RegisterType((*GetAccountsByIDsRequest)(nil), "acca.GetAccountsByIDsRequest")
	proto.RegisterType((*GetAccountsByIDsResponse)(nil), "acca.GetAccountsByIDsResponse")
	proto.RegisterType((*GetAccountsByKeyRequest)(nil), "acca.GetAccountsByKeyRequest")
	proto.RegisterType((*GetAccountsByKeyResponse)(nil), "acca.GetAccountsByKeyResponse")
	proto.RegisterType((*GetAccountsByUserIDRequest)(nil), "acca.GetAccountsByUserIDRequest")
	proto.RegisterType((*GetAccountsByUserIDResponse)(nil), "acca.GetAccountsByUserIDResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*CreateCurrencyResponse, error)
	GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	GetAccountsByIDs(ctx context.Context, in *GetAccountsByIDsRequest, opts ...grpc.CallOption) (*GetAccountsByIDsResponse, error)
	GetAccountsByKey(ctx context.Context, in *GetAccountsByKeyRequest, opts ...grpc.CallOption) (*GetAccountsByKeyResponse, error)
	GetAccountsByUserID(ctx context.Context, in *GetAccountsByUserIDRequest, opts ...grpc.CallOption) (*GetAccountsByUserIDResponse, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*CreateCurrencyResponse, error) {
	out := new(CreateCurrencyResponse)
	err := c.cc.Invoke(ctx, "/acca.Accounts/CreateCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error) {
	out := new(GetCurrenciesResponse)
	err := c.cc.Invoke(ctx, "/acca.Accounts/GetCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/acca.Accounts/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccountsByIDs(ctx context.Context, in *GetAccountsByIDsRequest, opts ...grpc.CallOption) (*GetAccountsByIDsResponse, error) {
	out := new(GetAccountsByIDsResponse)
	err := c.cc.Invoke(ctx, "/acca.Accounts/GetAccountsByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccountsByKey(ctx context.Context, in *GetAccountsByKeyRequest, opts ...grpc.CallOption) (*GetAccountsByKeyResponse, error) {
	out := new(GetAccountsByKeyResponse)
	err := c.cc.Invoke(ctx, "/acca.Accounts/GetAccountsByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccountsByUserID(ctx context.Context, in *GetAccountsByUserIDRequest, opts ...grpc.CallOption) (*GetAccountsByUserIDResponse, error) {
	out := new(GetAccountsByUserIDResponse)
	err := c.cc.Invoke(ctx, "/acca.Accounts/GetAccountsByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	CreateCurrency(context.Context, *CreateCurrencyRequest) (*CreateCurrencyResponse, error)
	GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error)
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	GetAccountsByIDs(context.Context, *GetAccountsByIDsRequest) (*GetAccountsByIDsResponse, error)
	GetAccountsByKey(context.Context, *GetAccountsByKeyRequest) (*GetAccountsByKeyResponse, error)
	GetAccountsByUserID(context.Context, *GetAccountsByUserIDRequest) (*GetAccountsByUserIDResponse, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_CreateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Accounts/CreateCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateCurrency(ctx, req.(*CreateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Accounts/GetCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetCurrencies(ctx, req.(*GetCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Accounts/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccountsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccountsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Accounts/GetAccountsByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccountsByIDs(ctx, req.(*GetAccountsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccountsByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccountsByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Accounts/GetAccountsByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccountsByKey(ctx, req.(*GetAccountsByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccountsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccountsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Accounts/GetAccountsByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccountsByUserID(ctx, req.(*GetAccountsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acca.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCurrency",
			Handler:    _Accounts_CreateCurrency_Handler,
		},
		{
			MethodName: "GetCurrencies",
			Handler:    _Accounts_GetCurrencies_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Accounts_CreateAccount_Handler,
		},
		{
			MethodName: "GetAccountsByIDs",
			Handler:    _Accounts_GetAccountsByIDs_Handler,
		},
		{
			MethodName: "GetAccountsByKey",
			Handler:    _Accounts_GetAccountsByKey_Handler,
		},
		{
			MethodName: "GetAccountsByUserID",
			Handler:    _Accounts_GetAccountsByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/acca/accounts.proto",
}

func init() { proto.RegisterFile("api/acca/accounts.proto", fileDescriptor_accounts_0e69909454bdbf9b) }

var fileDescriptor_accounts_0e69909454bdbf9b = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xe3, 0x36, 0x34, 0x13, 0x52, 0x55, 0x4b, 0x42, 0xa2, 0x0d, 0x1f, 0x61, 0x05, 0x52,
	0x10, 0x92, 0x91, 0x82, 0x50, 0x5b, 0x6e, 0xd0, 0x56, 0x91, 0xa9, 0x7a, 0x31, 0x82, 0x13, 0x12,
	0x5a, 0xec, 0x39, 0x44, 0xb4, 0x71, 0xf0, 0xae, 0x91, 0xfc, 0x63, 0xf8, 0x27, 0xfc, 0x31, 0x6e,
	0xc8, 0xfb, 0xe1, 0xda, 0x66, 0x53, 0x09, 0x89, 0x4b, 0x94, 0x9d, 0x99, 0xf7, 0x66, 0xe6, 0xed,
	0x5b, 0xc3, 0x98, 0x6f, 0x56, 0x2f, 0x79, 0x1c, 0xf3, 0xf2, 0x27, 0xcd, 0xd7, 0x52, 0x04, 0x9b,
	0x2c, 0x95, 0x29, 0xd9, 0x2d, 0x83, 0x74, 0x54, 0xa5, 0xaf, 0xd3, 0x04, 0xaf, 0x4c, 0x92, 0xfd,
	0xf4, 0x60, 0x74, 0x9a, 0x21, 0x97, 0x78, 0x9a, 0x67, 0x19, 0xae, 0xe3, 0x22, 0xc2, 0xef, 0x39,
	0x0a, 0x49, 0x0e, 0xc1, 0xff, 0x86, 0xc5, 0xc4, 0x9b, 0x79, 0xf3, 0x5e, 0x54, 0xfe, 0x25, 0x27,
	0xb0, 0x7b, 0x8d, 0x92, 0x4f, 0x3a, 0x33, 0x7f, 0xde, 0x5f, 0x3c, 0x0b, 0x4a, 0xb6, 0xc0, 0x09,
	0x0e, 0x2e, 0x51, 0xf2, 0xf3, 0xb5, 0xcc, 0x8a, 0x48, 0x41, 0xe8, 0x11, 0xf4, 0xaa, 0x90, 0x83,
	0x79, 0x08, 0x7b, 0x3f, 0xf8, 0x55, 0x8e, 0x93, 0x8e, 0x8a, 0xe9, 0xc3, 0x9b, 0xce, 0xb1, 0xc7,
	0x4e, 0xe0, 0x7e, 0xbb, 0x83, 0xd8, 0xa4, 0x6b, 0x81, 0xe4, 0x31, 0xf4, 0x63, 0x13, 0xfb, 0xb2,
	0x4a, 0x14, 0x9b, 0x1f, 0x81, 0x0d, 0x85, 0x09, 0x9b, 0xc3, 0x70, 0x89, 0xd2, 0xe0, 0x56, 0x28,
	0xb6, 0x2e, 0xc6, 0x96, 0x30, 0x6a, 0x55, 0x9a, 0x1e, 0x01, 0x58, 0xc2, 0x15, 0x8a, 0x89, 0xa7,
	0xf6, 0x3e, 0x30, 0x7b, 0xdb, 0x79, 0x6a, 0x15, 0xec, 0x97, 0x07, 0x43, 0x3d, 0xee, 0x5b, 0x7d,
	0x07, 0xdb, 0xc5, 0x6c, 0x8d, 0xdf, 0x69, 0x8f, 0x4f, 0x8e, 0x8d, 0xda, 0xbe, 0xea, 0xfa, 0xb4,
	0xae, 0x76, 0x93, 0xfc, 0xff, 0x89, 0x1d, 0x58, 0x2f, 0x54, 0x0d, 0x8c, 0x0e, 0x23, 0xe8, 0xf2,
	0x38, 0xbe, 0x91, 0x79, 0x8f, 0xc7, 0x71, 0x98, 0xb0, 0x05, 0x8c, 0x97, 0x28, 0x4d, 0xb1, 0x78,
	0x57, 0x84, 0x67, 0x95, 0xc8, 0x63, 0xb8, 0xa3, 0x11, 0x5a, 0x36, 0x3f, 0xea, 0x2a, 0x88, 0x60,
	0xe7, 0x30, 0xf9, 0x1b, 0x63, 0xda, 0x3c, 0x87, 0x7d, 0xeb, 0x5d, 0x23, 0xf6, 0x40, 0xaf, 0x6d,
	0xe7, 0xa9, 0xd2, 0xec, 0x45, 0xab, 0xf5, 0x05, 0xba, 0x8c, 0xeb, 0xeb, 0xfb, 0x6d, 0xf7, 0x54,
	0xc5, 0xff, 0xde, 0xf3, 0x35, 0xd0, 0x06, 0xcd, 0x47, 0x81, 0x59, 0x78, 0x56, 0xdb, 0x38, 0x17,
	0x98, 0x59, 0x91, 0x7a, 0x51, 0xb7, 0x3c, 0x86, 0x09, 0xfb, 0x04, 0x53, 0x27, 0xcc, 0x0c, 0x70,
	0x04, 0x03, 0x85, 0xab, 0x4d, 0xe1, 0xcd, 0xfb, 0x0b, 0xa2, 0xa7, 0x28, 0x8b, 0x2d, 0x34, 0xba,
	0x9b, 0xd7, 0x4e, 0x8b, 0xdf, 0x3e, 0xec, 0xdb, 0x03, 0xb9, 0x84, 0x83, 0xe6, 0x3b, 0x21, 0xd3,
	0x5b, 0xde, 0x27, 0x7d, 0xe0, 0x4e, 0xea, 0x91, 0xd8, 0x0e, 0x79, 0x0f, 0x83, 0xc6, 0x8b, 0x20,
	0x54, 0x03, 0x5c, 0x0f, 0x8a, 0x4e, 0x9d, 0xb9, 0x3a, 0x57, 0xc3, 0x55, 0x96, 0xcb, 0xe5, 0x65,
	0x3a, 0x75, 0xe6, 0x2a, 0xae, 0x0f, 0x70, 0xd8, 0x76, 0x0f, 0x79, 0x58, 0xb5, 0x77, 0x39, 0x91,
	0x3e, 0xda, 0x96, 0xde, 0x4a, 0x7a, 0x81, 0x85, 0x93, 0xf4, 0xc6, 0x63, 0x4e, 0xd2, 0x9a, 0xab,
	0xd8, 0x0e, 0xf9, 0x0c, 0xf7, 0x1c, 0xb7, 0x4e, 0x66, 0x0e, 0x60, 0xc3, 0x47, 0xf4, 0xc9, 0x2d,
	0x15, 0x96, 0xfd, 0x6b, 0x57, 0x7d, 0xbd, 0x5f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x85,
	0x72, 0x80, 0xf5, 0x05, 0x00, 0x00,
}
