// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/acca/models.proto

package acca

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Currency struct {
	CurrId               int64             `protobuf:"varint,1,opt,name=curr_id,json=currId,proto3" json:"curr_id,omitempty"`
	Key                  string            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_7a9a22422f7ee79a, []int{0}
}
func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (dst *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(dst, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetCurrId() int64 {
	if m != nil {
		return m.CurrId
	}
	return 0
}

func (m *Currency) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Currency) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type BalanceShortInfo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	AccId                int64    `protobuf:"varint,3,opt,name=acc_id,json=accId,proto3" json:"acc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceShortInfo) Reset()         { *m = BalanceShortInfo{} }
func (m *BalanceShortInfo) String() string { return proto.CompactTextString(m) }
func (*BalanceShortInfo) ProtoMessage()    {}
func (*BalanceShortInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_7a9a22422f7ee79a, []int{1}
}
func (m *BalanceShortInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceShortInfo.Unmarshal(m, b)
}
func (m *BalanceShortInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceShortInfo.Marshal(b, m, deterministic)
}
func (dst *BalanceShortInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceShortInfo.Merge(dst, src)
}
func (m *BalanceShortInfo) XXX_Size() int {
	return xxx_messageInfo_BalanceShortInfo.Size(m)
}
func (m *BalanceShortInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceShortInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceShortInfo proto.InternalMessageInfo

func (m *BalanceShortInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BalanceShortInfo) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *BalanceShortInfo) GetAccId() int64 {
	if m != nil {
		return m.AccId
	}
	return 0
}

type Account struct {
	AccId                int64             `protobuf:"varint,1,opt,name=acc_id,json=accId,proto3" json:"acc_id,omitempty"`
	CurrId               int64             `protobuf:"varint,2,opt,name=curr_id,json=currId,proto3" json:"curr_id,omitempty"`
	Key                  string            `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Balance              int64             `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Curr                 *Currency         `protobuf:"bytes,6,opt,name=curr,proto3" json:"curr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_7a9a22422f7ee79a, []int{2}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccId() int64 {
	if m != nil {
		return m.AccId
	}
	return 0
}

func (m *Account) GetCurrId() int64 {
	if m != nil {
		return m.CurrId
	}
	return 0
}

func (m *Account) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Account) GetCurr() *Currency {
	if m != nil {
		return m.Curr
	}
	return nil
}

type UserAccounts struct {
	UserId               string              `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balances             []*BalanceShortInfo `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserAccounts) Reset()         { *m = UserAccounts{} }
func (m *UserAccounts) String() string { return proto.CompactTextString(m) }
func (*UserAccounts) ProtoMessage()    {}
func (*UserAccounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_7a9a22422f7ee79a, []int{3}
}
func (m *UserAccounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccounts.Unmarshal(m, b)
}
func (m *UserAccounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccounts.Marshal(b, m, deterministic)
}
func (dst *UserAccounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccounts.Merge(dst, src)
}
func (m *UserAccounts) XXX_Size() int {
	return xxx_messageInfo_UserAccounts.Size(m)
}
func (m *UserAccounts) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccounts.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccounts proto.InternalMessageInfo

func (m *UserAccounts) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserAccounts) GetBalances() []*BalanceShortInfo {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*Currency)(nil), "acca.Currency")
	proto.RegisterMapType((map[string]string)(nil), "acca.Currency.MetaEntry")
	proto.RegisterType((*BalanceShortInfo)(nil), "acca.BalanceShortInfo")
	proto.RegisterType((*Account)(nil), "acca.Account")
	proto.RegisterMapType((map[string]string)(nil), "acca.Account.MetaEntry")
	proto.RegisterType((*UserAccounts)(nil), "acca.UserAccounts")
}

func init() { proto.RegisterFile("api/acca/models.proto", fileDescriptor_models_7a9a22422f7ee79a) }

var fileDescriptor_models_7a9a22422f7ee79a = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x49, 0xd3, 0x75, 0xdb, 0x9b, 0xc8, 0x08, 0xce, 0x05, 0x4f, 0xa5, 0xa7, 0x82, 0xd2,
	0xc1, 0x3c, 0x28, 0xde, 0x54, 0x3c, 0xf4, 0xe0, 0x25, 0x22, 0x1e, 0x3c, 0x48, 0x96, 0x46, 0x1c,
	0x6e, 0xed, 0x48, 0x53, 0xa1, 0xdf, 0xc5, 0xef, 0xe8, 0x57, 0x90, 0xa4, 0x59, 0xd7, 0x0d, 0x4f,
	0xde, 0xf2, 0x92, 0x3f, 0xff, 0xff, 0x7b, 0xbf, 0x17, 0x98, 0xf0, 0xcd, 0x72, 0xc6, 0x85, 0xe0,
	0xb3, 0x75, 0x91, 0xc9, 0x55, 0x99, 0x6c, 0x54, 0xa1, 0x0b, 0xe2, 0x9b, 0xab, 0xe8, 0x1b, 0xc1,
	0xe0, 0xbe, 0x52, 0x4a, 0xe6, 0xa2, 0x26, 0x53, 0xe8, 0x8b, 0x4a, 0xa9, 0xb7, 0x65, 0x46, 0x51,
	0x88, 0x62, 0xcc, 0x02, 0x53, 0xa6, 0x19, 0x19, 0x03, 0xfe, 0x94, 0x35, 0xf5, 0x42, 0x14, 0x0f,
	0x99, 0x39, 0x92, 0x0b, 0xf0, 0xd7, 0x52, 0x73, 0x8a, 0x43, 0x1c, 0x8f, 0xe6, 0x34, 0x31, 0x66,
	0xc9, 0xd6, 0x28, 0x79, 0x94, 0x9a, 0x3f, 0xe4, 0x5a, 0xd5, 0xcc, 0xaa, 0xce, 0xae, 0x60, 0xd8,
	0x5e, 0x6d, 0xcd, 0xd0, 0xce, 0xec, 0x04, 0x7a, 0x5f, 0x7c, 0x55, 0x49, 0x17, 0xd0, 0x14, 0x37,
	0xde, 0x35, 0x8a, 0x5e, 0x60, 0x7c, 0xc7, 0x57, 0x3c, 0x17, 0xf2, 0xe9, 0xa3, 0x50, 0x3a, 0xcd,
	0xdf, 0x0b, 0x42, 0xc0, 0xd7, 0xf5, 0x46, 0x3a, 0x03, 0x7b, 0x26, 0x14, 0xfa, 0x8b, 0x46, 0x67,
	0x3d, 0x30, 0xdb, 0x96, 0x64, 0x02, 0x01, 0x17, 0xc2, 0x8c, 0x84, 0xed, 0x43, 0x8f, 0x0b, 0x91,
	0x66, 0xd1, 0x0f, 0x82, 0xfe, 0xad, 0x10, 0x45, 0x95, 0xeb, 0x8e, 0x04, 0x75, 0x24, 0x5d, 0x1a,
	0xde, 0x5f, 0x34, 0xf0, 0x6e, 0x80, 0x4e, 0xbc, 0xbf, 0x1f, 0x7f, 0xee, 0x38, 0xf5, 0x2c, 0xa7,
	0x69, 0xc3, 0xc9, 0x05, 0x1f, 0x62, 0x22, 0x11, 0xf8, 0x26, 0x82, 0x06, 0x21, 0x8a, 0x47, 0xf3,
	0xe3, 0x7d, 0xa8, 0xcc, 0xbe, 0xfd, 0x1f, 0xe5, 0x2b, 0x1c, 0x3d, 0x97, 0x52, 0xb9, 0xec, 0xd2,
	0x8c, 0x57, 0x95, 0xb2, 0x5d, 0xf6, 0x90, 0x05, 0xa6, 0x4c, 0x33, 0x32, 0x87, 0x81, 0xeb, 0xbe,
	0xa4, 0x9e, 0x6d, 0xfb, 0xb4, 0xe9, 0xe4, 0x70, 0x13, 0xac, 0xd5, 0x2d, 0x02, 0xfb, 0xa7, 0x2e,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x02, 0xe5, 0x68, 0x6c, 0x02, 0x00, 0x00,
}
