// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/acca/transfer.proto

package acca

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewTransferRequest struct {
	Opers                []*TxOper         `protobuf:"bytes,1,rep,name=opers" json:"opers,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,2,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Reason               string            `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewTransferRequest) Reset()         { *m = NewTransferRequest{} }
func (m *NewTransferRequest) String() string { return proto.CompactTextString(m) }
func (*NewTransferRequest) ProtoMessage()    {}
func (*NewTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{0}
}
func (m *NewTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NewTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NewTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *NewTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransferRequest.Merge(dst, src)
}
func (m *NewTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *NewTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransferRequest proto.InternalMessageInfo

func (m *NewTransferRequest) GetOpers() []*TxOper {
	if m != nil {
		return m.Opers
	}
	return nil
}

func (m *NewTransferRequest) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NewTransferRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type NewTransferResponse struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTransferResponse) Reset()         { *m = NewTransferResponse{} }
func (m *NewTransferResponse) String() string { return proto.CompactTextString(m) }
func (*NewTransferResponse) ProtoMessage()    {}
func (*NewTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{1}
}
func (m *NewTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NewTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NewTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *NewTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransferResponse.Merge(dst, src)
}
func (m *NewTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *NewTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransferResponse proto.InternalMessageInfo

func (m *NewTransferResponse) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type AcceptTxRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptTxRequest) Reset()         { *m = AcceptTxRequest{} }
func (m *AcceptTxRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptTxRequest) ProtoMessage()    {}
func (*AcceptTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{2}
}
func (m *AcceptTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AcceptTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AcceptTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *AcceptTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptTxRequest.Merge(dst, src)
}
func (m *AcceptTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *AcceptTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptTxRequest proto.InternalMessageInfo

func (m *AcceptTxRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type AcceptTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptTxResponse) Reset()         { *m = AcceptTxResponse{} }
func (m *AcceptTxResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptTxResponse) ProtoMessage()    {}
func (*AcceptTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{3}
}
func (m *AcceptTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AcceptTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AcceptTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *AcceptTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptTxResponse.Merge(dst, src)
}
func (m *AcceptTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *AcceptTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptTxResponse proto.InternalMessageInfo

type RejectTxRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectTxRequest) Reset()         { *m = RejectTxRequest{} }
func (m *RejectTxRequest) String() string { return proto.CompactTextString(m) }
func (*RejectTxRequest) ProtoMessage()    {}
func (*RejectTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{4}
}
func (m *RejectTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RejectTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RejectTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RejectTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectTxRequest.Merge(dst, src)
}
func (m *RejectTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *RejectTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectTxRequest proto.InternalMessageInfo

func (m *RejectTxRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type RejectTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectTxResponse) Reset()         { *m = RejectTxResponse{} }
func (m *RejectTxResponse) String() string { return proto.CompactTextString(m) }
func (*RejectTxResponse) ProtoMessage()    {}
func (*RejectTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{5}
}
func (m *RejectTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RejectTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RejectTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RejectTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectTxResponse.Merge(dst, src)
}
func (m *RejectTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *RejectTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectTxResponse proto.InternalMessageInfo

type RollbackTxRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackTxRequest) Reset()         { *m = RollbackTxRequest{} }
func (m *RollbackTxRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackTxRequest) ProtoMessage()    {}
func (*RollbackTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{6}
}
func (m *RollbackTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RollbackTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RollbackTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RollbackTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackTxRequest.Merge(dst, src)
}
func (m *RollbackTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *RollbackTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackTxRequest proto.InternalMessageInfo

func (m *RollbackTxRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type RollbackTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackTxResponse) Reset()         { *m = RollbackTxResponse{} }
func (m *RollbackTxResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackTxResponse) ProtoMessage()    {}
func (*RollbackTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{7}
}
func (m *RollbackTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RollbackTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RollbackTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RollbackTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackTxResponse.Merge(dst, src)
}
func (m *RollbackTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *RollbackTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackTxResponse proto.InternalMessageInfo

type HandleRequestsRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequestsRequest) Reset()         { *m = HandleRequestsRequest{} }
func (m *HandleRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*HandleRequestsRequest) ProtoMessage()    {}
func (*HandleRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{8}
}
func (m *HandleRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HandleRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HandleRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *HandleRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequestsRequest.Merge(dst, src)
}
func (m *HandleRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *HandleRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequestsRequest proto.InternalMessageInfo

func (m *HandleRequestsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type HandleRequestsResponse struct {
	NumOk                int64    `protobuf:"varint,1,opt,name=num_ok,json=numOk,proto3" json:"num_ok,omitempty"`
	NumErr               int64    `protobuf:"varint,2,opt,name=num_err,json=numErr,proto3" json:"num_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequestsResponse) Reset()         { *m = HandleRequestsResponse{} }
func (m *HandleRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*HandleRequestsResponse) ProtoMessage()    {}
func (*HandleRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{9}
}
func (m *HandleRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HandleRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HandleRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *HandleRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequestsResponse.Merge(dst, src)
}
func (m *HandleRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *HandleRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequestsResponse proto.InternalMessageInfo

func (m *HandleRequestsResponse) GetNumOk() int64 {
	if m != nil {
		return m.NumOk
	}
	return 0
}

func (m *HandleRequestsResponse) GetNumErr() int64 {
	if m != nil {
		return m.NumErr
	}
	return 0
}

type GetUpdatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUpdatesRequest) Reset()         { *m = GetUpdatesRequest{} }
func (m *GetUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetUpdatesRequest) ProtoMessage()    {}
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{10}
}
func (m *GetUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetUpdatesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUpdatesRequest.Merge(dst, src)
}
func (m *GetUpdatesRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUpdatesRequest proto.InternalMessageInfo

type Update struct {
	// Types that are valid to be assigned to Type:
	//	*Update_OperStatus
	//	*Update_TxStatus
	Type                 isUpdate_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{11}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Update.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return m.Size()
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

type isUpdate_Type interface {
	isUpdate_Type()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Update_OperStatus struct {
	OperStatus *Update_OperUpdateStatus `protobuf:"bytes,1,opt,name=oper_status,json=operStatus,oneof"`
}
type Update_TxStatus struct {
	TxStatus *Update_TxUpdateStatus `protobuf:"bytes,2,opt,name=tx_status,json=txStatus,oneof"`
}

func (*Update_OperStatus) isUpdate_Type() {}
func (*Update_TxStatus) isUpdate_Type()   {}

func (m *Update) GetType() isUpdate_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Update) GetOperStatus() *Update_OperUpdateStatus {
	if x, ok := m.GetType().(*Update_OperStatus); ok {
		return x.OperStatus
	}
	return nil
}

func (m *Update) GetTxStatus() *Update_TxUpdateStatus {
	if x, ok := m.GetType().(*Update_TxStatus); ok {
		return x.TxStatus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Update) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Update_OneofMarshaler, _Update_OneofUnmarshaler, _Update_OneofSizer, []interface{}{
		(*Update_OperStatus)(nil),
		(*Update_TxStatus)(nil),
	}
}

func _Update_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Update)
	// type
	switch x := m.Type.(type) {
	case *Update_OperStatus:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OperStatus); err != nil {
			return err
		}
	case *Update_TxStatus:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TxStatus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Update.Type has unexpected type %T", x)
	}
	return nil
}

func _Update_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Update)
	switch tag {
	case 1: // type.oper_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Update_OperUpdateStatus)
		err := b.DecodeMessage(msg)
		m.Type = &Update_OperStatus{msg}
		return true, err
	case 2: // type.tx_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Update_TxUpdateStatus)
		err := b.DecodeMessage(msg)
		m.Type = &Update_TxStatus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Update_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Update)
	// type
	switch x := m.Type.(type) {
	case *Update_OperStatus:
		s := proto.Size(x.OperStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Update_TxStatus:
		s := proto.Size(x.TxStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Update_OperUpdateStatus struct {
	OperId               int64    `protobuf:"varint,1,opt,name=oper_id,json=operId,proto3" json:"oper_id,omitempty"`
	SrcAccId             int64    `protobuf:"varint,2,opt,name=src_acc_id,json=srcAccId,proto3" json:"src_acc_id,omitempty"`
	DstAccId             int64    `protobuf:"varint,3,opt,name=dst_acc_id,json=dstAccId,proto3" json:"dst_acc_id,omitempty"`
	NewStatus            string   `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Amount               int64    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	TxId                 int64    `protobuf:"varint,7,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update_OperUpdateStatus) Reset()         { *m = Update_OperUpdateStatus{} }
func (m *Update_OperUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*Update_OperUpdateStatus) ProtoMessage()    {}
func (*Update_OperUpdateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{11, 0}
}
func (m *Update_OperUpdateStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Update_OperUpdateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Update_OperUpdateStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Update_OperUpdateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update_OperUpdateStatus.Merge(dst, src)
}
func (m *Update_OperUpdateStatus) XXX_Size() int {
	return m.Size()
}
func (m *Update_OperUpdateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Update_OperUpdateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Update_OperUpdateStatus proto.InternalMessageInfo

func (m *Update_OperUpdateStatus) GetOperId() int64 {
	if m != nil {
		return m.OperId
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetSrcAccId() int64 {
	if m != nil {
		return m.SrcAccId
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetDstAccId() int64 {
	if m != nil {
		return m.DstAccId
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

func (m *Update_OperUpdateStatus) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Update_OperUpdateStatus) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type Update_TxUpdateStatus struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	NewStatus            string   `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update_TxUpdateStatus) Reset()         { *m = Update_TxUpdateStatus{} }
func (m *Update_TxUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*Update_TxUpdateStatus) ProtoMessage()    {}
func (*Update_TxUpdateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_fe100db7ea94be47, []int{11, 1}
}
func (m *Update_TxUpdateStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Update_TxUpdateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Update_TxUpdateStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Update_TxUpdateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update_TxUpdateStatus.Merge(dst, src)
}
func (m *Update_TxUpdateStatus) XXX_Size() int {
	return m.Size()
}
func (m *Update_TxUpdateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Update_TxUpdateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Update_TxUpdateStatus proto.InternalMessageInfo

func (m *Update_TxUpdateStatus) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *Update_TxUpdateStatus) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*NewTransferRequest)(nil), "acca.NewTransferRequest")
	proto.RegisterMapType((map[string]string)(nil), "acca.NewTransferRequest.MetaEntry")
	proto.RegisterType((*NewTransferResponse)(nil), "acca.NewTransferResponse")
	proto.RegisterType((*AcceptTxRequest)(nil), "acca.AcceptTxRequest")
	proto.RegisterType((*AcceptTxResponse)(nil), "acca.AcceptTxResponse")
	proto.RegisterType((*RejectTxRequest)(nil), "acca.RejectTxRequest")
	proto.RegisterType((*RejectTxResponse)(nil), "acca.RejectTxResponse")
	proto.RegisterType((*RollbackTxRequest)(nil), "acca.RollbackTxRequest")
	proto.RegisterType((*RollbackTxResponse)(nil), "acca.RollbackTxResponse")
	proto.RegisterType((*HandleRequestsRequest)(nil), "acca.HandleRequestsRequest")
	proto.RegisterType((*HandleRequestsResponse)(nil), "acca.HandleRequestsResponse")
	proto.RegisterType((*GetUpdatesRequest)(nil), "acca.GetUpdatesRequest")
	proto.RegisterType((*Update)(nil), "acca.Update")
	proto.RegisterType((*Update_OperUpdateStatus)(nil), "acca.Update.OperUpdateStatus")
	proto.RegisterType((*Update_TxUpdateStatus)(nil), "acca.Update.TxUpdateStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Transfer service

type TransferClient interface {
	NewTransfer(ctx context.Context, in *NewTransferRequest, opts ...grpc.CallOption) (*NewTransferResponse, error)
	AcceptTx(ctx context.Context, in *AcceptTxRequest, opts ...grpc.CallOption) (*AcceptTxResponse, error)
	RejectTx(ctx context.Context, in *RejectTxRequest, opts ...grpc.CallOption) (*RejectTxResponse, error)
	RollbackTx(ctx context.Context, in *RollbackTxRequest, opts ...grpc.CallOption) (*RollbackTxResponse, error)
	HandleRequests(ctx context.Context, in *HandleRequestsRequest, opts ...grpc.CallOption) (*HandleRequestsResponse, error)
	GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (Transfer_GetUpdatesClient, error)
}

type transferClient struct {
	cc *grpc.ClientConn
}

func NewTransferClient(cc *grpc.ClientConn) TransferClient {
	return &transferClient{cc}
}

func (c *transferClient) NewTransfer(ctx context.Context, in *NewTransferRequest, opts ...grpc.CallOption) (*NewTransferResponse, error) {
	out := new(NewTransferResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/NewTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) AcceptTx(ctx context.Context, in *AcceptTxRequest, opts ...grpc.CallOption) (*AcceptTxResponse, error) {
	out := new(AcceptTxResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/AcceptTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) RejectTx(ctx context.Context, in *RejectTxRequest, opts ...grpc.CallOption) (*RejectTxResponse, error) {
	out := new(RejectTxResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/RejectTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) RollbackTx(ctx context.Context, in *RollbackTxRequest, opts ...grpc.CallOption) (*RollbackTxResponse, error) {
	out := new(RollbackTxResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/RollbackTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) HandleRequests(ctx context.Context, in *HandleRequestsRequest, opts ...grpc.CallOption) (*HandleRequestsResponse, error) {
	out := new(HandleRequestsResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/HandleRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (Transfer_GetUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Transfer_serviceDesc.Streams[0], "/acca.Transfer/GetUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferGetUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transfer_GetUpdatesClient interface {
	Recv() (*Update, error)
	grpc.ClientStream
}

type transferGetUpdatesClient struct {
	grpc.ClientStream
}

func (x *transferGetUpdatesClient) Recv() (*Update, error) {
	m := new(Update)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Transfer service

type TransferServer interface {
	NewTransfer(context.Context, *NewTransferRequest) (*NewTransferResponse, error)
	AcceptTx(context.Context, *AcceptTxRequest) (*AcceptTxResponse, error)
	RejectTx(context.Context, *RejectTxRequest) (*RejectTxResponse, error)
	RollbackTx(context.Context, *RollbackTxRequest) (*RollbackTxResponse, error)
	HandleRequests(context.Context, *HandleRequestsRequest) (*HandleRequestsResponse, error)
	GetUpdates(*GetUpdatesRequest, Transfer_GetUpdatesServer) error
}

func RegisterTransferServer(s *grpc.Server, srv TransferServer) {
	s.RegisterService(&_Transfer_serviceDesc, srv)
}

func _Transfer_NewTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).NewTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/NewTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).NewTransfer(ctx, req.(*NewTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_AcceptTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).AcceptTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/AcceptTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).AcceptTx(ctx, req.(*AcceptTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_RejectTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).RejectTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/RejectTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).RejectTx(ctx, req.(*RejectTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_RollbackTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).RollbackTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/RollbackTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).RollbackTx(ctx, req.(*RollbackTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_HandleRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).HandleRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/HandleRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).HandleRequests(ctx, req.(*HandleRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_GetUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferServer).GetUpdates(m, &transferGetUpdatesServer{stream})
}

type Transfer_GetUpdatesServer interface {
	Send(*Update) error
	grpc.ServerStream
}

type transferGetUpdatesServer struct {
	grpc.ServerStream
}

func (x *transferGetUpdatesServer) Send(m *Update) error {
	return x.ServerStream.SendMsg(m)
}

var _Transfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acca.Transfer",
	HandlerType: (*TransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTransfer",
			Handler:    _Transfer_NewTransfer_Handler,
		},
		{
			MethodName: "AcceptTx",
			Handler:    _Transfer_AcceptTx_Handler,
		},
		{
			MethodName: "RejectTx",
			Handler:    _Transfer_RejectTx_Handler,
		},
		{
			MethodName: "RollbackTx",
			Handler:    _Transfer_RollbackTx_Handler,
		},
		{
			MethodName: "HandleRequests",
			Handler:    _Transfer_HandleRequests_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUpdates",
			Handler:       _Transfer_GetUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/acca/transfer.proto",
}

func (m *NewTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Opers) > 0 {
		for _, msg := range m.Opers {
			dAtA[i] = 0xa
			i++
			i = encodeVarintTransfer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Meta) > 0 {
		for k, _ := range m.Meta {
			dAtA[i] = 0x12
			i++
			v := m.Meta[k]
			mapSize := 1 + len(k) + sovTransfer(uint64(len(k))) + 1 + len(v) + sovTransfer(uint64(len(v)))
			i = encodeVarintTransfer(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTransfer(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintTransfer(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.Reason) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.Reason)))
		i += copy(dAtA[i:], m.Reason)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *NewTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TxId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *AcceptTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AcceptTxRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TxId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *AcceptTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AcceptTxResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RejectTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RejectTxRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TxId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RejectTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RejectTxResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RollbackTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RollbackTxRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TxId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RollbackTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RollbackTxResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *HandleRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HandleRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.Limit))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *HandleRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HandleRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NumOk != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.NumOk))
	}
	if m.NumErr != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.NumErr))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *GetUpdatesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUpdatesRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Update) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Update) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != nil {
		nn1, err := m.Type.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Update_OperStatus) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.OperStatus != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.OperStatus.Size()))
		n2, err := m.OperStatus.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}
func (m *Update_TxStatus) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.TxStatus != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxStatus.Size()))
		n3, err := m.TxStatus.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}
func (m *Update_OperUpdateStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Update_OperUpdateStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.OperId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.OperId))
	}
	if m.SrcAccId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.SrcAccId))
	}
	if m.DstAccId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.DstAccId))
	}
	if len(m.NewStatus) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.NewStatus)))
		i += copy(dAtA[i:], m.NewStatus)
	}
	if m.Amount != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.Amount))
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if m.TxId != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Update_TxUpdateStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Update_TxUpdateStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TxId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(m.TxId))
	}
	if len(m.NewStatus) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTransfer(dAtA, i, uint64(len(m.NewStatus)))
		i += copy(dAtA[i:], m.NewStatus)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintTransfer(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *NewTransferRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.Opers) > 0 {
		for _, e := range m.Opers {
			l = e.Size()
			n += 1 + l + sovTransfer(uint64(l))
		}
	}
	if len(m.Meta) > 0 {
		for k, v := range m.Meta {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTransfer(uint64(len(k))) + 1 + len(v) + sovTransfer(uint64(len(v)))
			n += mapEntrySize + 1 + sovTransfer(uint64(mapEntrySize))
		}
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *NewTransferResponse) Size() (n int) {
	var l int
	_ = l
	if m.TxId != 0 {
		n += 1 + sovTransfer(uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AcceptTxRequest) Size() (n int) {
	var l int
	_ = l
	if m.TxId != 0 {
		n += 1 + sovTransfer(uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AcceptTxResponse) Size() (n int) {
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RejectTxRequest) Size() (n int) {
	var l int
	_ = l
	if m.TxId != 0 {
		n += 1 + sovTransfer(uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RejectTxResponse) Size() (n int) {
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RollbackTxRequest) Size() (n int) {
	var l int
	_ = l
	if m.TxId != 0 {
		n += 1 + sovTransfer(uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RollbackTxResponse) Size() (n int) {
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HandleRequestsRequest) Size() (n int) {
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovTransfer(uint64(m.Limit))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HandleRequestsResponse) Size() (n int) {
	var l int
	_ = l
	if m.NumOk != 0 {
		n += 1 + sovTransfer(uint64(m.NumOk))
	}
	if m.NumErr != 0 {
		n += 1 + sovTransfer(uint64(m.NumErr))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetUpdatesRequest) Size() (n int) {
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Update) Size() (n int) {
	var l int
	_ = l
	if m.Type != nil {
		n += m.Type.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Update_OperStatus) Size() (n int) {
	var l int
	_ = l
	if m.OperStatus != nil {
		l = m.OperStatus.Size()
		n += 1 + l + sovTransfer(uint64(l))
	}
	return n
}
func (m *Update_TxStatus) Size() (n int) {
	var l int
	_ = l
	if m.TxStatus != nil {
		l = m.TxStatus.Size()
		n += 1 + l + sovTransfer(uint64(l))
	}
	return n
}
func (m *Update_OperUpdateStatus) Size() (n int) {
	var l int
	_ = l
	if m.OperId != 0 {
		n += 1 + sovTransfer(uint64(m.OperId))
	}
	if m.SrcAccId != 0 {
		n += 1 + sovTransfer(uint64(m.SrcAccId))
	}
	if m.DstAccId != 0 {
		n += 1 + sovTransfer(uint64(m.DstAccId))
	}
	l = len(m.NewStatus)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTransfer(uint64(m.Amount))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	if m.TxId != 0 {
		n += 1 + sovTransfer(uint64(m.TxId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Update_TxUpdateStatus) Size() (n int) {
	var l int
	_ = l
	if m.TxId != 0 {
		n += 1 + sovTransfer(uint64(m.TxId))
	}
	l = len(m.NewStatus)
	if l > 0 {
		n += 1 + l + sovTransfer(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTransfer(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTransfer(x uint64) (n int) {
	return sovTransfer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NewTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Opers = append(m.Opers, &TxOper{})
			if err := m.Opers[len(m.Opers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTransfer
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTransfer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTransfer
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTransfer
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTransfer
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTransfer(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTransfer
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Meta[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NewTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AcceptTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AcceptTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AcceptTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AcceptTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AcceptTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AcceptTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RejectTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RejectTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RejectTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RejectTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RejectTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RejectTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RollbackTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RollbackTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RollbackTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RollbackTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RollbackTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RollbackTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HandleRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HandleRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HandleRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HandleRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HandleRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HandleRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumOk", wireType)
			}
			m.NumOk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumOk |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumErr", wireType)
			}
			m.NumErr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumErr |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUpdatesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUpdatesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUpdatesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Update) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Update: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Update: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Update_OperUpdateStatus{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Type = &Update_OperStatus{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Update_TxUpdateStatus{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Type = &Update_TxStatus{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Update_OperUpdateStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OperUpdateStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OperUpdateStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperId", wireType)
			}
			m.OperId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OperId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcAccId", wireType)
			}
			m.SrcAccId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcAccId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstAccId", wireType)
			}
			m.DstAccId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DstAccId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Update_TxUpdateStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxUpdateStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxUpdateStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			m.TxId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransfer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransfer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTransfer
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTransfer
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTransfer(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTransfer = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransfer   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api/acca/transfer.proto", fileDescriptor_transfer_fe100db7ea94be47) }

var fileDescriptor_transfer_fe100db7ea94be47 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0xe3, 0xc4, 0x4d, 0x26, 0x55, 0xff, 0x74, 0xdb, 0xa4, 0xfe, 0x4d, 0x1b, 0x55, 0x3e,
	0xa0, 0x0a, 0x89, 0x14, 0x15, 0x89, 0xa2, 0x72, 0xa1, 0x55, 0x2b, 0xda, 0x43, 0xa9, 0x64, 0xc2,
	0x39, 0xda, 0xae, 0x17, 0x29, 0x24, 0xb1, 0xcd, 0xee, 0x86, 0xba, 0x0f, 0x82, 0xc4, 0x89, 0x77,
	0xe1, 0x04, 0x47, 0x1e, 0x01, 0x85, 0x17, 0x41, 0xbb, 0xeb, 0x8d, 0x13, 0x27, 0x08, 0x6e, 0x3b,
	0xf3, 0x7d, 0xdf, 0xcc, 0xec, 0x7a, 0x3e, 0xc3, 0x0e, 0x4e, 0x06, 0x87, 0x98, 0x10, 0x7c, 0x28,
	0x18, 0x8e, 0xf8, 0x3b, 0xca, 0xba, 0x09, 0x8b, 0x45, 0x8c, 0x2a, 0x32, 0xe9, 0xb5, 0x66, 0xf0,
	0x38, 0x0e, 0xe9, 0x88, 0x6b, 0xd0, 0xff, 0x6a, 0x01, 0x7a, 0x4d, 0xef, 0x7a, 0x99, 0x24, 0xa0,
	0x1f, 0x26, 0x94, 0x0b, 0xe4, 0x43, 0x35, 0x4e, 0x28, 0xe3, 0xae, 0xb5, 0x6f, 0x1f, 0x34, 0x8e,
	0xd6, 0xbb, 0x52, 0xd9, 0xed, 0xa5, 0x37, 0x09, 0x65, 0x81, 0x86, 0xd0, 0x33, 0xa8, 0x8c, 0xa9,
	0xc0, 0x6e, 0x59, 0x51, 0x7c, 0x4d, 0x59, 0xae, 0xd5, 0xbd, 0xa6, 0x02, 0x5f, 0x44, 0x82, 0xdd,
	0x07, 0x8a, 0x8f, 0xda, 0xe0, 0x30, 0x8a, 0x79, 0x1c, 0xb9, 0xf6, 0xbe, 0x75, 0x50, 0x0f, 0xb2,
	0xc8, 0x3b, 0x86, 0xfa, 0x8c, 0x8a, 0x9a, 0x60, 0x0f, 0xe9, 0xbd, 0x6b, 0x29, 0x86, 0x3c, 0xa2,
	0x6d, 0xa8, 0x7e, 0xc4, 0xa3, 0x09, 0x75, 0xcb, 0x2a, 0xa7, 0x83, 0x93, 0xf2, 0x73, 0xcb, 0x7f,
	0x04, 0x5b, 0x0b, 0x6d, 0x79, 0x12, 0x47, 0x9c, 0xa2, 0x2d, 0xa8, 0x8a, 0xb4, 0x3f, 0x08, 0x55,
	0x11, 0x3b, 0xa8, 0x88, 0xf4, 0x2a, 0xf4, 0x1f, 0xc2, 0x7f, 0xa7, 0x84, 0xd0, 0x44, 0xf4, 0x52,
	0x73, 0xd7, 0x95, 0x3c, 0x04, 0xcd, 0x9c, 0xa7, 0x0b, 0x4a, 0x6d, 0x40, 0xdf, 0x53, 0xf2, 0x0f,
	0xda, 0x9c, 0x97, 0x69, 0x0f, 0x60, 0x33, 0x88, 0x47, 0xa3, 0x5b, 0x4c, 0x86, 0x7f, 0x51, 0x6f,
	0x03, 0x9a, 0x67, 0x66, 0xfa, 0xc7, 0xd0, 0xba, 0xc4, 0x51, 0x38, 0xa2, 0x99, 0x96, 0x9b, 0x1a,
	0xdb, 0x50, 0x1d, 0x0d, 0xc6, 0x03, 0x91, 0xd5, 0xd0, 0x81, 0x7f, 0x09, 0xed, 0x22, 0x3d, 0x7b,
	0x95, 0x16, 0x38, 0xd1, 0x64, 0xdc, 0x8f, 0x87, 0x46, 0x10, 0x4d, 0xc6, 0x37, 0x43, 0xb4, 0x03,
	0x6b, 0x32, 0x4d, 0x19, 0x53, 0xef, 0x6b, 0x07, 0x92, 0x75, 0xc1, 0x98, 0xbf, 0x05, 0x9b, 0xaf,
	0xa8, 0x78, 0x9b, 0x84, 0x58, 0x50, 0xd3, 0xd4, 0xff, 0x62, 0x83, 0xa3, 0x53, 0xe8, 0x25, 0x34,
	0xe4, 0x3a, 0xf4, 0xb9, 0xc0, 0x62, 0xc2, 0x55, 0xd1, 0xc6, 0xd1, 0x9e, 0x5e, 0x06, 0x4d, 0xe9,
	0xca, 0xa5, 0xd1, 0xc7, 0x37, 0x8a, 0x74, 0x59, 0x0a, 0x40, 0x6a, 0x74, 0x84, 0x4e, 0xa0, 0x2e,
	0x52, 0xa3, 0x2f, 0x2b, 0xfd, 0x83, 0x05, 0x7d, 0x2f, 0x2d, 0xa8, 0x6b, 0x22, 0xd5, 0x67, 0xef,
	0x9b, 0x05, 0xcd, 0x62, 0x79, 0x79, 0x17, 0x35, 0xd2, 0xec, 0x61, 0x1d, 0x19, 0x5e, 0x85, 0x68,
	0x17, 0x80, 0x33, 0xd2, 0xc7, 0x84, 0x48, 0x4c, 0xdf, 0xb3, 0xc6, 0x19, 0x39, 0x25, 0x44, 0xa3,
	0x21, 0x17, 0x06, 0xb5, 0x35, 0x1a, 0x72, 0xa1, 0xd1, 0x3d, 0x80, 0x88, 0xde, 0x99, 0x31, 0x2b,
	0x6a, 0x07, 0xeb, 0x11, 0xbd, 0xcb, 0x7a, 0xb6, 0xc1, 0xc1, 0xe3, 0x78, 0x12, 0x09, 0xb7, 0xaa,
	0x5b, 0xea, 0x08, 0x21, 0xa8, 0x88, 0xfb, 0x84, 0xba, 0x8e, 0x12, 0xa8, 0x73, 0xfe, 0xd9, 0xd7,
	0xf2, 0xcf, 0xee, 0x9d, 0xc3, 0xc6, 0xe2, 0x3d, 0x57, 0x6e, 0x47, 0x61, 0x8c, 0x72, 0x61, 0x8c,
	0x33, 0x47, 0xb7, 0x3b, 0xfa, 0x64, 0x43, 0xcd, 0x18, 0x02, 0x9d, 0x43, 0x63, 0xce, 0x1f, 0xc8,
	0xfd, 0x93, 0x53, 0xbd, 0xff, 0x57, 0x20, 0xd9, 0xfe, 0x95, 0xd0, 0x0b, 0xa8, 0x19, 0x47, 0xa0,
	0x96, 0x26, 0x16, 0x9c, 0xe4, 0xb5, 0x8b, 0xe9, 0x79, 0xb1, 0xb1, 0x84, 0x11, 0x17, 0xac, 0x64,
	0xc4, 0x4b, 0xce, 0x29, 0xa1, 0x53, 0x80, 0xdc, 0x11, 0x68, 0x27, 0xe3, 0x15, 0xdd, 0xe4, 0xb9,
	0xcb, 0xc0, 0xac, 0xc4, 0x35, 0x6c, 0x2c, 0xfa, 0x01, 0x65, 0x2b, 0xb6, 0xd2, 0x54, 0xde, 0xee,
	0x6a, 0x70, 0x56, 0xee, 0x18, 0x20, 0x37, 0x85, 0x99, 0x68, 0xc9, 0x26, 0xde, 0xfa, 0xfc, 0x1a,
	0xfb, 0xa5, 0x27, 0xd6, 0x59, 0xf3, 0xfb, 0xb4, 0x63, 0xfd, 0x98, 0x76, 0xac, 0x9f, 0xd3, 0x8e,
	0xf5, 0xf9, 0x57, 0xa7, 0x74, 0xeb, 0xa8, 0xff, 0xf0, 0xd3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb4, 0x00, 0xcc, 0x72, 0xbf, 0x05, 0x00, 0x00,
}
