// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/acca/transfer.proto

package acca

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewTransferRequest struct {
	Opers                []*NewTransferRequestOper `protobuf:"bytes,1,rep,name=opers,proto3" json:"opers,omitempty"`
	Meta                 map[string]string         `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NewTransferRequest) Reset()         { *m = NewTransferRequest{} }
func (m *NewTransferRequest) String() string { return proto.CompactTextString(m) }
func (*NewTransferRequest) ProtoMessage()    {}
func (*NewTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{0}
}
func (m *NewTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransferRequest.Unmarshal(m, b)
}
func (m *NewTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransferRequest.Marshal(b, m, deterministic)
}
func (dst *NewTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransferRequest.Merge(dst, src)
}
func (m *NewTransferRequest) XXX_Size() int {
	return xxx_messageInfo_NewTransferRequest.Size(m)
}
func (m *NewTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransferRequest proto.InternalMessageInfo

func (m *NewTransferRequest) GetOpers() []*NewTransferRequestOper {
	if m != nil {
		return m.Opers
	}
	return nil
}

func (m *NewTransferRequest) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type NewTransferRequestOper struct {
	SrcAccId             int64             `protobuf:"varint,1,opt,name=src_acc_id,json=srcAccId,proto3" json:"src_acc_id,omitempty"`
	DstAccId             int64             `protobuf:"varint,2,opt,name=dst_acc_id,json=dstAccId,proto3" json:"dst_acc_id,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount               int64             `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason               string            `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Hold                 bool              `protobuf:"varint,7,opt,name=hold,proto3" json:"hold,omitempty"`
	HoldAccId            int64             `protobuf:"varint,8,opt,name=hold_acc_id,json=holdAccId,proto3" json:"hold_acc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewTransferRequestOper) Reset()         { *m = NewTransferRequestOper{} }
func (m *NewTransferRequestOper) String() string { return proto.CompactTextString(m) }
func (*NewTransferRequestOper) ProtoMessage()    {}
func (*NewTransferRequestOper) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{0, 0}
}
func (m *NewTransferRequestOper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransferRequestOper.Unmarshal(m, b)
}
func (m *NewTransferRequestOper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransferRequestOper.Marshal(b, m, deterministic)
}
func (dst *NewTransferRequestOper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransferRequestOper.Merge(dst, src)
}
func (m *NewTransferRequestOper) XXX_Size() int {
	return xxx_messageInfo_NewTransferRequestOper.Size(m)
}
func (m *NewTransferRequestOper) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransferRequestOper.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransferRequestOper proto.InternalMessageInfo

func (m *NewTransferRequestOper) GetSrcAccId() int64 {
	if m != nil {
		return m.SrcAccId
	}
	return 0
}

func (m *NewTransferRequestOper) GetDstAccId() int64 {
	if m != nil {
		return m.DstAccId
	}
	return 0
}

func (m *NewTransferRequestOper) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewTransferRequestOper) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *NewTransferRequestOper) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *NewTransferRequestOper) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NewTransferRequestOper) GetHold() bool {
	if m != nil {
		return m.Hold
	}
	return false
}

func (m *NewTransferRequestOper) GetHoldAccId() int64 {
	if m != nil {
		return m.HoldAccId
	}
	return 0
}

type NewTransferResponse struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTransferResponse) Reset()         { *m = NewTransferResponse{} }
func (m *NewTransferResponse) String() string { return proto.CompactTextString(m) }
func (*NewTransferResponse) ProtoMessage()    {}
func (*NewTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{1}
}
func (m *NewTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTransferResponse.Unmarshal(m, b)
}
func (m *NewTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTransferResponse.Marshal(b, m, deterministic)
}
func (dst *NewTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTransferResponse.Merge(dst, src)
}
func (m *NewTransferResponse) XXX_Size() int {
	return xxx_messageInfo_NewTransferResponse.Size(m)
}
func (m *NewTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTransferResponse proto.InternalMessageInfo

func (m *NewTransferResponse) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type AcceptTxRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptTxRequest) Reset()         { *m = AcceptTxRequest{} }
func (m *AcceptTxRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptTxRequest) ProtoMessage()    {}
func (*AcceptTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{2}
}
func (m *AcceptTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptTxRequest.Unmarshal(m, b)
}
func (m *AcceptTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptTxRequest.Marshal(b, m, deterministic)
}
func (dst *AcceptTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptTxRequest.Merge(dst, src)
}
func (m *AcceptTxRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptTxRequest.Size(m)
}
func (m *AcceptTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptTxRequest proto.InternalMessageInfo

func (m *AcceptTxRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type AcceptTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptTxResponse) Reset()         { *m = AcceptTxResponse{} }
func (m *AcceptTxResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptTxResponse) ProtoMessage()    {}
func (*AcceptTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{3}
}
func (m *AcceptTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptTxResponse.Unmarshal(m, b)
}
func (m *AcceptTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptTxResponse.Marshal(b, m, deterministic)
}
func (dst *AcceptTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptTxResponse.Merge(dst, src)
}
func (m *AcceptTxResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptTxResponse.Size(m)
}
func (m *AcceptTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptTxResponse proto.InternalMessageInfo

type RejectTxRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectTxRequest) Reset()         { *m = RejectTxRequest{} }
func (m *RejectTxRequest) String() string { return proto.CompactTextString(m) }
func (*RejectTxRequest) ProtoMessage()    {}
func (*RejectTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{4}
}
func (m *RejectTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectTxRequest.Unmarshal(m, b)
}
func (m *RejectTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectTxRequest.Marshal(b, m, deterministic)
}
func (dst *RejectTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectTxRequest.Merge(dst, src)
}
func (m *RejectTxRequest) XXX_Size() int {
	return xxx_messageInfo_RejectTxRequest.Size(m)
}
func (m *RejectTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectTxRequest proto.InternalMessageInfo

func (m *RejectTxRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type RejectTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectTxResponse) Reset()         { *m = RejectTxResponse{} }
func (m *RejectTxResponse) String() string { return proto.CompactTextString(m) }
func (*RejectTxResponse) ProtoMessage()    {}
func (*RejectTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{5}
}
func (m *RejectTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectTxResponse.Unmarshal(m, b)
}
func (m *RejectTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectTxResponse.Marshal(b, m, deterministic)
}
func (dst *RejectTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectTxResponse.Merge(dst, src)
}
func (m *RejectTxResponse) XXX_Size() int {
	return xxx_messageInfo_RejectTxResponse.Size(m)
}
func (m *RejectTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectTxResponse proto.InternalMessageInfo

type RollbackTxRequest struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackTxRequest) Reset()         { *m = RollbackTxRequest{} }
func (m *RollbackTxRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackTxRequest) ProtoMessage()    {}
func (*RollbackTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{6}
}
func (m *RollbackTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackTxRequest.Unmarshal(m, b)
}
func (m *RollbackTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackTxRequest.Marshal(b, m, deterministic)
}
func (dst *RollbackTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackTxRequest.Merge(dst, src)
}
func (m *RollbackTxRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackTxRequest.Size(m)
}
func (m *RollbackTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackTxRequest proto.InternalMessageInfo

func (m *RollbackTxRequest) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type RollbackTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackTxResponse) Reset()         { *m = RollbackTxResponse{} }
func (m *RollbackTxResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackTxResponse) ProtoMessage()    {}
func (*RollbackTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{7}
}
func (m *RollbackTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackTxResponse.Unmarshal(m, b)
}
func (m *RollbackTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackTxResponse.Marshal(b, m, deterministic)
}
func (dst *RollbackTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackTxResponse.Merge(dst, src)
}
func (m *RollbackTxResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackTxResponse.Size(m)
}
func (m *RollbackTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackTxResponse proto.InternalMessageInfo

type HandleRequestsRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequestsRequest) Reset()         { *m = HandleRequestsRequest{} }
func (m *HandleRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*HandleRequestsRequest) ProtoMessage()    {}
func (*HandleRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{8}
}
func (m *HandleRequestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleRequestsRequest.Unmarshal(m, b)
}
func (m *HandleRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleRequestsRequest.Marshal(b, m, deterministic)
}
func (dst *HandleRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequestsRequest.Merge(dst, src)
}
func (m *HandleRequestsRequest) XXX_Size() int {
	return xxx_messageInfo_HandleRequestsRequest.Size(m)
}
func (m *HandleRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequestsRequest proto.InternalMessageInfo

func (m *HandleRequestsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type HandleRequestsResponse struct {
	NumOk                int64    `protobuf:"varint,1,opt,name=num_ok,json=numOk,proto3" json:"num_ok,omitempty"`
	NumErr               int64    `protobuf:"varint,2,opt,name=num_err,json=numErr,proto3" json:"num_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequestsResponse) Reset()         { *m = HandleRequestsResponse{} }
func (m *HandleRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*HandleRequestsResponse) ProtoMessage()    {}
func (*HandleRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{9}
}
func (m *HandleRequestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleRequestsResponse.Unmarshal(m, b)
}
func (m *HandleRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleRequestsResponse.Marshal(b, m, deterministic)
}
func (dst *HandleRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequestsResponse.Merge(dst, src)
}
func (m *HandleRequestsResponse) XXX_Size() int {
	return xxx_messageInfo_HandleRequestsResponse.Size(m)
}
func (m *HandleRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequestsResponse proto.InternalMessageInfo

func (m *HandleRequestsResponse) GetNumOk() int64 {
	if m != nil {
		return m.NumOk
	}
	return 0
}

func (m *HandleRequestsResponse) GetNumErr() int64 {
	if m != nil {
		return m.NumErr
	}
	return 0
}

type GetUpdatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUpdatesRequest) Reset()         { *m = GetUpdatesRequest{} }
func (m *GetUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetUpdatesRequest) ProtoMessage()    {}
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{10}
}
func (m *GetUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUpdatesRequest.Unmarshal(m, b)
}
func (m *GetUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUpdatesRequest.Marshal(b, m, deterministic)
}
func (dst *GetUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUpdatesRequest.Merge(dst, src)
}
func (m *GetUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetUpdatesRequest.Size(m)
}
func (m *GetUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUpdatesRequest proto.InternalMessageInfo

type Update struct {
	// Types that are valid to be assigned to Type:
	//	*Update_OperStatus
	//	*Update_TxStatus
	Type                 isUpdate_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{11}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

type isUpdate_Type interface {
	isUpdate_Type()
}

type Update_OperStatus struct {
	OperStatus *Update_OperUpdateStatus `protobuf:"bytes,1,opt,name=oper_status,json=operStatus,proto3,oneof"`
}

type Update_TxStatus struct {
	TxStatus *Update_TxUpdateStatus `protobuf:"bytes,2,opt,name=tx_status,json=txStatus,proto3,oneof"`
}

func (*Update_OperStatus) isUpdate_Type() {}

func (*Update_TxStatus) isUpdate_Type() {}

func (m *Update) GetType() isUpdate_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Update) GetOperStatus() *Update_OperUpdateStatus {
	if x, ok := m.GetType().(*Update_OperStatus); ok {
		return x.OperStatus
	}
	return nil
}

func (m *Update) GetTxStatus() *Update_TxUpdateStatus {
	if x, ok := m.GetType().(*Update_TxStatus); ok {
		return x.TxStatus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Update) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Update_OneofMarshaler, _Update_OneofUnmarshaler, _Update_OneofSizer, []interface{}{
		(*Update_OperStatus)(nil),
		(*Update_TxStatus)(nil),
	}
}

func _Update_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Update)
	// type
	switch x := m.Type.(type) {
	case *Update_OperStatus:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OperStatus); err != nil {
			return err
		}
	case *Update_TxStatus:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TxStatus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Update.Type has unexpected type %T", x)
	}
	return nil
}

func _Update_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Update)
	switch tag {
	case 1: // type.oper_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Update_OperUpdateStatus)
		err := b.DecodeMessage(msg)
		m.Type = &Update_OperStatus{msg}
		return true, err
	case 2: // type.tx_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Update_TxUpdateStatus)
		err := b.DecodeMessage(msg)
		m.Type = &Update_TxStatus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Update_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Update)
	// type
	switch x := m.Type.(type) {
	case *Update_OperStatus:
		s := proto.Size(x.OperStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Update_TxStatus:
		s := proto.Size(x.TxStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Update_OperUpdateStatus struct {
	OperId               int64    `protobuf:"varint,1,opt,name=oper_id,json=operId,proto3" json:"oper_id,omitempty"`
	SrcAccId             int64    `protobuf:"varint,2,opt,name=src_acc_id,json=srcAccId,proto3" json:"src_acc_id,omitempty"`
	DstAccId             int64    `protobuf:"varint,3,opt,name=dst_acc_id,json=dstAccId,proto3" json:"dst_acc_id,omitempty"`
	NewStatus            string   `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Amount               int64    `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	TxId                 int64    `protobuf:"varint,7,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update_OperUpdateStatus) Reset()         { *m = Update_OperUpdateStatus{} }
func (m *Update_OperUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*Update_OperUpdateStatus) ProtoMessage()    {}
func (*Update_OperUpdateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{11, 0}
}
func (m *Update_OperUpdateStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update_OperUpdateStatus.Unmarshal(m, b)
}
func (m *Update_OperUpdateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update_OperUpdateStatus.Marshal(b, m, deterministic)
}
func (dst *Update_OperUpdateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update_OperUpdateStatus.Merge(dst, src)
}
func (m *Update_OperUpdateStatus) XXX_Size() int {
	return xxx_messageInfo_Update_OperUpdateStatus.Size(m)
}
func (m *Update_OperUpdateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Update_OperUpdateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Update_OperUpdateStatus proto.InternalMessageInfo

func (m *Update_OperUpdateStatus) GetOperId() int64 {
	if m != nil {
		return m.OperId
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetSrcAccId() int64 {
	if m != nil {
		return m.SrcAccId
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetDstAccId() int64 {
	if m != nil {
		return m.DstAccId
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

func (m *Update_OperUpdateStatus) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Update_OperUpdateStatus) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Update_OperUpdateStatus) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

type Update_TxUpdateStatus struct {
	TxId                 int64    `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	NewStatus            string   `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update_TxUpdateStatus) Reset()         { *m = Update_TxUpdateStatus{} }
func (m *Update_TxUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*Update_TxUpdateStatus) ProtoMessage()    {}
func (*Update_TxUpdateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_transfer_499d1451867a1ecb, []int{11, 1}
}
func (m *Update_TxUpdateStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update_TxUpdateStatus.Unmarshal(m, b)
}
func (m *Update_TxUpdateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update_TxUpdateStatus.Marshal(b, m, deterministic)
}
func (dst *Update_TxUpdateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update_TxUpdateStatus.Merge(dst, src)
}
func (m *Update_TxUpdateStatus) XXX_Size() int {
	return xxx_messageInfo_Update_TxUpdateStatus.Size(m)
}
func (m *Update_TxUpdateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Update_TxUpdateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Update_TxUpdateStatus proto.InternalMessageInfo

func (m *Update_TxUpdateStatus) GetTxId() int64 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *Update_TxUpdateStatus) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*NewTransferRequest)(nil), "acca.NewTransferRequest")
	proto.RegisterMapType((map[string]string)(nil), "acca.NewTransferRequest.MetaEntry")
	proto.RegisterType((*NewTransferRequestOper)(nil), "acca.NewTransferRequest.oper")
	proto.RegisterMapType((map[string]string)(nil), "acca.NewTransferRequest.oper.MetaEntry")
	proto.RegisterType((*NewTransferResponse)(nil), "acca.NewTransferResponse")
	proto.RegisterType((*AcceptTxRequest)(nil), "acca.AcceptTxRequest")
	proto.RegisterType((*AcceptTxResponse)(nil), "acca.AcceptTxResponse")
	proto.RegisterType((*RejectTxRequest)(nil), "acca.RejectTxRequest")
	proto.RegisterType((*RejectTxResponse)(nil), "acca.RejectTxResponse")
	proto.RegisterType((*RollbackTxRequest)(nil), "acca.RollbackTxRequest")
	proto.RegisterType((*RollbackTxResponse)(nil), "acca.RollbackTxResponse")
	proto.RegisterType((*HandleRequestsRequest)(nil), "acca.HandleRequestsRequest")
	proto.RegisterType((*HandleRequestsResponse)(nil), "acca.HandleRequestsResponse")
	proto.RegisterType((*GetUpdatesRequest)(nil), "acca.GetUpdatesRequest")
	proto.RegisterType((*Update)(nil), "acca.Update")
	proto.RegisterType((*Update_OperUpdateStatus)(nil), "acca.Update.OperUpdateStatus")
	proto.RegisterType((*Update_TxUpdateStatus)(nil), "acca.Update.TxUpdateStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferClient is the client API for Transfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferClient interface {
	NewTransfer(ctx context.Context, in *NewTransferRequest, opts ...grpc.CallOption) (*NewTransferResponse, error)
	AcceptTx(ctx context.Context, in *AcceptTxRequest, opts ...grpc.CallOption) (*AcceptTxResponse, error)
	RejectTx(ctx context.Context, in *RejectTxRequest, opts ...grpc.CallOption) (*RejectTxResponse, error)
	RollbackTx(ctx context.Context, in *RollbackTxRequest, opts ...grpc.CallOption) (*RollbackTxResponse, error)
	HandleRequests(ctx context.Context, in *HandleRequestsRequest, opts ...grpc.CallOption) (*HandleRequestsResponse, error)
	GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (Transfer_GetUpdatesClient, error)
}

type transferClient struct {
	cc *grpc.ClientConn
}

func NewTransferClient(cc *grpc.ClientConn) TransferClient {
	return &transferClient{cc}
}

func (c *transferClient) NewTransfer(ctx context.Context, in *NewTransferRequest, opts ...grpc.CallOption) (*NewTransferResponse, error) {
	out := new(NewTransferResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/NewTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) AcceptTx(ctx context.Context, in *AcceptTxRequest, opts ...grpc.CallOption) (*AcceptTxResponse, error) {
	out := new(AcceptTxResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/AcceptTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) RejectTx(ctx context.Context, in *RejectTxRequest, opts ...grpc.CallOption) (*RejectTxResponse, error) {
	out := new(RejectTxResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/RejectTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) RollbackTx(ctx context.Context, in *RollbackTxRequest, opts ...grpc.CallOption) (*RollbackTxResponse, error) {
	out := new(RollbackTxResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/RollbackTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) HandleRequests(ctx context.Context, in *HandleRequestsRequest, opts ...grpc.CallOption) (*HandleRequestsResponse, error) {
	out := new(HandleRequestsResponse)
	err := c.cc.Invoke(ctx, "/acca.Transfer/HandleRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) GetUpdates(ctx context.Context, in *GetUpdatesRequest, opts ...grpc.CallOption) (Transfer_GetUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Transfer_serviceDesc.Streams[0], "/acca.Transfer/GetUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferGetUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transfer_GetUpdatesClient interface {
	Recv() (*Update, error)
	grpc.ClientStream
}

type transferGetUpdatesClient struct {
	grpc.ClientStream
}

func (x *transferGetUpdatesClient) Recv() (*Update, error) {
	m := new(Update)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransferServer is the server API for Transfer service.
type TransferServer interface {
	NewTransfer(context.Context, *NewTransferRequest) (*NewTransferResponse, error)
	AcceptTx(context.Context, *AcceptTxRequest) (*AcceptTxResponse, error)
	RejectTx(context.Context, *RejectTxRequest) (*RejectTxResponse, error)
	RollbackTx(context.Context, *RollbackTxRequest) (*RollbackTxResponse, error)
	HandleRequests(context.Context, *HandleRequestsRequest) (*HandleRequestsResponse, error)
	GetUpdates(*GetUpdatesRequest, Transfer_GetUpdatesServer) error
}

func RegisterTransferServer(s *grpc.Server, srv TransferServer) {
	s.RegisterService(&_Transfer_serviceDesc, srv)
}

func _Transfer_NewTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).NewTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/NewTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).NewTransfer(ctx, req.(*NewTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_AcceptTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).AcceptTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/AcceptTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).AcceptTx(ctx, req.(*AcceptTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_RejectTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).RejectTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/RejectTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).RejectTx(ctx, req.(*RejectTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_RollbackTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).RollbackTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/RollbackTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).RollbackTx(ctx, req.(*RollbackTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_HandleRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).HandleRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acca.Transfer/HandleRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).HandleRequests(ctx, req.(*HandleRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_GetUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferServer).GetUpdates(m, &transferGetUpdatesServer{stream})
}

type Transfer_GetUpdatesServer interface {
	Send(*Update) error
	grpc.ServerStream
}

type transferGetUpdatesServer struct {
	grpc.ServerStream
}

func (x *transferGetUpdatesServer) Send(m *Update) error {
	return x.ServerStream.SendMsg(m)
}

var _Transfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acca.Transfer",
	HandlerType: (*TransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTransfer",
			Handler:    _Transfer_NewTransfer_Handler,
		},
		{
			MethodName: "AcceptTx",
			Handler:    _Transfer_AcceptTx_Handler,
		},
		{
			MethodName: "RejectTx",
			Handler:    _Transfer_RejectTx_Handler,
		},
		{
			MethodName: "RollbackTx",
			Handler:    _Transfer_RollbackTx_Handler,
		},
		{
			MethodName: "HandleRequests",
			Handler:    _Transfer_HandleRequests_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUpdates",
			Handler:       _Transfer_GetUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/acca/transfer.proto",
}

func init() { proto.RegisterFile("api/acca/transfer.proto", fileDescriptor_transfer_499d1451867a1ecb) }

var fileDescriptor_transfer_499d1451867a1ecb = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe3, 0x8f, 0xb8, 0xf1, 0x04, 0x95, 0x76, 0xfb, 0x65, 0x4c, 0x8b, 0x22, 0x1f, 0x20,
	0x42, 0x22, 0x45, 0xad, 0x44, 0x51, 0x7b, 0xa1, 0xa8, 0x15, 0xed, 0xa1, 0x54, 0x32, 0xe5, 0x1c,
	0x6d, 0xed, 0x45, 0x84, 0x24, 0xb6, 0xd9, 0xdd, 0xd0, 0xf4, 0x41, 0xb8, 0xf2, 0x0c, 0xbc, 0x05,
	0x4f, 0xc3, 0x3b, 0xa0, 0xfd, 0x8a, 0x13, 0x27, 0x2d, 0x88, 0x53, 0x77, 0x67, 0xfe, 0xff, 0xf1,
	0x8c, 0x3d, 0xbf, 0x06, 0xb6, 0x70, 0xd1, 0xdb, 0xc5, 0x49, 0x82, 0x77, 0x39, 0xc5, 0x19, 0xfb,
	0x44, 0x68, 0xa7, 0xa0, 0x39, 0xcf, 0x91, 0x2b, 0x82, 0xd1, 0x6f, 0x07, 0xd0, 0x7b, 0x72, 0x73,
	0xa5, 0x73, 0x31, 0xf9, 0x3a, 0x22, 0x8c, 0xa3, 0x7d, 0xa8, 0xe7, 0x05, 0xa1, 0x2c, 0xb0, 0x5a,
	0x4e, 0xbb, 0xb9, 0xb7, 0xd3, 0x11, 0xe2, 0xce, 0xbc, 0xb0, 0x23, 0x54, 0xb1, 0xd2, 0xa2, 0x57,
	0xe0, 0x0e, 0x09, 0xc7, 0x81, 0x2d, 0x3d, 0xd1, 0x9d, 0x9e, 0x0b, 0xc2, 0xf1, 0x69, 0xc6, 0xe9,
	0x6d, 0x2c, 0xf5, 0xe1, 0x4f, 0x1b, 0x5c, 0x51, 0x01, 0x6d, 0x03, 0x30, 0x9a, 0x74, 0x71, 0x92,
	0x74, 0x7b, 0x69, 0x60, 0xb5, 0xac, 0xb6, 0x13, 0x37, 0x18, 0x4d, 0x8e, 0x93, 0xe4, 0x3c, 0x15,
	0xd9, 0x94, 0x71, 0x93, 0xb5, 0x55, 0x36, 0x65, 0x5c, 0x65, 0x11, 0xb8, 0xfc, 0xb6, 0x20, 0x81,
	0xd3, 0xb2, 0xda, 0x7e, 0x2c, 0xcf, 0x68, 0x13, 0x3c, 0x3c, 0xcc, 0x47, 0x19, 0x0f, 0x5c, 0xa9,
	0xd6, 0x37, 0x11, 0xa7, 0x04, 0xb3, 0x3c, 0x0b, 0xea, 0x52, 0xad, 0x6f, 0xe8, 0x48, 0x0f, 0xe0,
	0xc9, 0x01, 0x9e, 0xdd, 0x3b, 0x74, 0x75, 0x0a, 0xd1, 0xc0, 0xe7, 0x7c, 0x90, 0x06, 0x4b, 0x2d,
	0xab, 0xdd, 0x88, 0xe5, 0x19, 0x3d, 0x81, 0xa6, 0xf8, 0x6b, 0x7a, 0x6e, 0xc8, 0x2e, 0x7c, 0x11,
	0x92, 0x4d, 0x87, 0x07, 0xe0, 0x4f, 0xca, 0xa0, 0x15, 0x70, 0xfa, 0xe4, 0x56, 0x8e, 0xed, 0xc7,
	0xe2, 0x88, 0xd6, 0xa1, 0xfe, 0x0d, 0x0f, 0x46, 0x44, 0x0e, 0xeb, 0xc7, 0xea, 0x72, 0x68, 0xbf,
	0xb6, 0xfe, 0xdb, 0x18, 0x3d, 0x87, 0xb5, 0x99, 0x81, 0x58, 0x91, 0x67, 0x8c, 0xa0, 0x35, 0xa8,
	0xf3, 0x71, 0xf9, 0xd2, 0x5d, 0x3e, 0x3e, 0x4f, 0xa3, 0xa7, 0xf0, 0xf0, 0x38, 0x49, 0x48, 0xc1,
	0xaf, 0xc6, 0x66, 0x2f, 0x16, 0xea, 0x10, 0xac, 0x94, 0x3a, 0x55, 0x50, 0x78, 0x63, 0xf2, 0x85,
	0x24, 0xff, 0xe0, 0x2d, 0x75, 0xda, 0xdb, 0x86, 0xd5, 0x38, 0x1f, 0x0c, 0xae, 0x71, 0xd2, 0xff,
	0x8b, 0x7b, 0x1d, 0xd0, 0xb4, 0x52, 0xfb, 0x5f, 0xc0, 0xc6, 0x19, 0xce, 0xd2, 0x01, 0xd1, 0x5e,
	0x66, 0x6a, 0xac, 0x43, 0x7d, 0xd0, 0x1b, 0xf6, 0xb8, 0xae, 0xa1, 0x2e, 0xd1, 0x19, 0x6c, 0x56,
	0xe5, 0xfa, 0xad, 0x6c, 0x80, 0x97, 0x8d, 0x86, 0xdd, 0xbc, 0x6f, 0x0c, 0xd9, 0x68, 0x78, 0xd9,
	0x47, 0x5b, 0xb0, 0x24, 0xc2, 0x84, 0x52, 0xbd, 0x85, 0x42, 0x75, 0x4a, 0x69, 0xb4, 0x06, 0xab,
	0xef, 0x08, 0xff, 0x58, 0xa4, 0x98, 0x13, 0xf3, 0xd0, 0xe8, 0x87, 0x03, 0x9e, 0x0a, 0xa1, 0x37,
	0xd0, 0x14, 0xab, 0xd3, 0x65, 0x1c, 0xf3, 0x11, 0x93, 0x45, 0x27, 0x6c, 0x29, 0x49, 0xe7, 0xb2,
	0x20, 0x54, 0x1d, 0x3f, 0x48, 0xd1, 0x59, 0x2d, 0x06, 0xe1, 0x51, 0x37, 0x74, 0x08, 0x3e, 0x1f,
	0x1b, 0xbf, 0x2d, 0xfd, 0x8f, 0x67, 0xfc, 0x57, 0xe3, 0x8a, 0xbb, 0xc1, 0xc7, 0xea, 0x1c, 0xfe,
	0xb2, 0x60, 0xa5, 0x5a, 0x5e, 0xcc, 0x22, 0x5b, 0x9a, 0xbc, 0x58, 0x4f, 0x5c, 0x15, 0x6d, 0x53,
	0x2c, 0xda, 0xf7, 0xb2, 0xe8, 0x54, 0x58, 0xdc, 0x01, 0xc8, 0xc8, 0x8d, 0x69, 0xd3, 0x95, 0x3b,
	0xe8, 0x67, 0xe4, 0x46, 0x3f, 0xb3, 0xc4, 0xb2, 0x3e, 0x83, 0xa5, 0x41, 0xd8, 0x9b, 0x42, 0x78,
	0xf2, 0xd9, 0x97, 0xca, 0xcf, 0x1e, 0x9e, 0xc0, 0xf2, 0xec, 0x9c, 0x0b, 0xb7, 0xa3, 0xd2, 0x86,
	0x5d, 0x69, 0xe3, 0xad, 0xa7, 0x1e, 0xb7, 0xf7, 0xdd, 0x81, 0x86, 0x01, 0x02, 0x9d, 0x40, 0x73,
	0x8a, 0x0f, 0x14, 0xdc, 0xf5, 0x3f, 0x20, 0x7c, 0xb4, 0x20, 0xa3, 0xf7, 0xaf, 0x86, 0x8e, 0xa0,
	0x61, 0x88, 0x40, 0x1b, 0x4a, 0x58, 0x21, 0x29, 0xdc, 0xac, 0x86, 0xa7, 0xcd, 0x06, 0x09, 0x63,
	0xae, 0xa0, 0x64, 0xcc, 0x73, 0xe4, 0xd4, 0xd0, 0x31, 0x40, 0x49, 0x04, 0xda, 0xd2, 0xba, 0x2a,
	0x4d, 0x61, 0x30, 0x9f, 0x98, 0x94, 0xb8, 0x80, 0xe5, 0x59, 0x1e, 0x90, 0x5e, 0xb1, 0x85, 0x50,
	0x85, 0xdb, 0x8b, 0x93, 0x93, 0x72, 0x07, 0x00, 0x25, 0x14, 0xa6, 0xa3, 0x39, 0x4c, 0xc2, 0x07,
	0xd3, 0x6b, 0x1c, 0xd5, 0x5e, 0x5a, 0xd7, 0x9e, 0xfc, 0x9d, 0xda, 0xff, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xa0, 0x8f, 0x17, 0x39, 0xc2, 0x06, 0x00, 0x00,
}
