// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/update.proto

package api

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *GetUpdateRequest) Validate() error {
	return nil
}
func (this *UpdatedInvoice) Validate() error {
	return nil
}
func (this *UpdatedTransaction) Validate() error {
	return nil
}
func (this *Update) Validate() error {
	if oneOfNester, ok := this.GetType().(*Update_UpdatedInvoice); ok {
		if oneOfNester.UpdatedInvoice != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.UpdatedInvoice); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("UpdatedInvoice", err)
			}
		}
	}
	if oneOfNester, ok := this.GetType().(*Update_UpdatedTransaction); ok {
		if oneOfNester.UpdatedTransaction != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.UpdatedTransaction); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("UpdatedTransaction", err)
			}
		}
	}
	return nil
}
